### ISSUE TITLE
`Auto` MemoryUsage type causes crash.

### ISSUE THREAD

**Issue by isothiazol** [dust-engine/vk-mem-rs#4]
When using any of the `Auto` MemoryUsage flags, my project crashes with this error:
`Mapping memory without VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT set. Memory has type 0 which has properties VkMemoryPropertyFlags(0) The Vulkan spec states: memory must have been created with a memory type that reports VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT`.

All the other MemoryUsage types work, but are deprecated. What am I doing wrong?

**Comment by Neo-Zhixing** [comment]
Can you include a simple example program to demonstrate the issue?

Also, if incorrect memory bits were allocated, the issue most likely originated from the underlying VulkanMemoryAllocator project. This is only a Rust FFI wrapper.

**Comment by isothiazol** [comment]
I found a different memory management library that works just fine, and I'm sure a "simple example program" can't be that simple in the case of Vulkan.
